# wrangler.toml - Updated configuration with RSS monitoring
name = "grant-tracker-pro"
main = "functions/_worker.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration for frontend
[env.production]
name = "grant-tracker-pro"
route = { pattern = "grant-tracker-pro.pages.dev/*", zone_name = "pages.dev" }

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "GRANTS_KV"
id = "557129958b334182b8571299384b7781" # Replace with your actual KV namespace ID
preview_id = "your-preview-kv-namespace-id" # Replace with your preview KV namespace ID

# D1 Database (optional - for advanced queries)
[[d1_databases]]
binding = "GRANTS_D1"
database_name = "grant-tracker-db"
database_id = "a9ac718a-0663-4260-8b55-6c329b01c8cc" # Replace with your actual D1 database ID

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Grant Tracker Pro"

# Main grant search function
[[routes]]
pattern = "/api/search-grants"
script = "search-grants"

# RSS monitoring function  
[[routes]]
pattern = "/api/search-rss-grants"
script = "rss-monitor"

# RSS monitoring status endpoint
[[routes]]
pattern = "/api/rss-status"
script = "rss-monitor"

# Data persistence functions
[[routes]]
pattern = "/api/save-grants"
script = "save-grants"

[[routes]]
pattern = "/api/load-grants"
script = "save-grants"

# Worker configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "functions"

[build.upload]
format = "modules"
dir = "functions"
main = "./_worker.js"

# Scheduled RSS monitoring - runs every 2 hours
[triggers]
crons = ["0 */2 * * *"]  # Every 2 hours
script = "rss-monitor"

# Development configuration
[env.development]
name = "grant-tracker-pro-dev"
kv_namespaces = [
  { binding = "GRANTS_KV", id = "your-dev-kv-namespace-id" }
]

# Limits and settings
[limits]
cpu_ms = 100  # Increased for RSS processing

# Analytics (optional)
# [analytics_engine_datasets]
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Secrets (set these using: wrangler secret put SECRET_NAME)
# GRANTS_GOV_API_KEY = "your-grants-gov-api-key"
# FOUNDATION_DIRECTORY_API_KEY = "your-foundation-directory-api-key"
# RSS_WEBHOOK_URL = "your-webhook-url-for-notifications"